
User.create!(phone: '79781234567', role: 1, password: 'Zzasasas', password_confirmation: 'Zzasasas', first_name: 'Admin')

Dictionary.create!(language: 0, vocabulary: 0, category: 0, word: 'привет', translate: 'hi')
Dictionary.create!(language: 0, vocabulary: 0, category: 0, word: 'здравствуйте, привет', translate: 'hello')
Dictionary.create!(language: 0, vocabulary: 0, category: 0, word: 'извини(те)', translate: 'sorry')
Dictionary.create!(language: 0, vocabulary: 0, category: 0, word: 'пожалуйста(прошу); угождать', translate: 'please')
Dictionary.create!(language: 0, vocabulary: 0, category: 0, word: 'спасибо', translate: 'thank you')
Dictionary.create!(language: 0, vocabulary: 0, category: 0, word: 'пожалуйста, не за что', translate: 'you are welcome')
Dictionary.create!(language: 0, vocabulary: 0, category: 0, word: 'как жаль', translate: 'what a pity')
Dictionary.create!(language: 0, vocabulary: 0, category: 0, word: 'до свидания', translate: 'good bye')

Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'люди', translate: 'people')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'мужчина', translate: 'man')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'женщина', translate: 'woman')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'ребенок', translate: 'child')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'мальчик', translate: 'boy')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'девочка', translate: 'girl')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'парень', translate: 'guy')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'друг', translate: 'friend')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'знакомый; знакомство', translate: 'acquaintance')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'сосед', translate: 'neighbor')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'гость', translate: 'guest')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'начальник; шеф; главный; вождь', translate: 'chief')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'босс', translate: 'boss')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'конкурент; соперник', translate: 'competitor')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'клиент', translate: 'client')
Dictionary.create!(language: 0, vocabulary: 0, category: 1, word: 'коллега', translate: 'colleague')